require("dotenv").config();
const express = require("express");
const rootRouter = require("./routes/rootRouter.js");
const app = express();
const port = process.env.PORT;
const cors = require("cors");
app.use(cors());
app.use(express.json());
app.use("/api/v1", rootRouter);
app.listen(port, () => console.log("Server is listening on ", port));
